// import { FontSizeTokens, LineHeightTokens, FontWeightTokens, FontFamilyTokens, StrokeWidthTokens } from "@fluentui/tokens";
// import { NewBorderRadius, NewColorTokens, NewControlLayout, NewFontTokens, ThowAwayForTestingOnly } from "../types.js";

// export const generateNewColorTokens= (): NewColorTokens=> ({
//   colorControlBackgroundListItemIndicatorStrokeRest: 'rgba(0,0,0,0.45)',
//   colorControlBackgroundListItemIndicatorStrokeHover: '#6166AF',
//   colorControlBackgroundListItemIndicatorStrokePressed: '#7275C0',
//   colorControlBackgroundListItemIndicatorStrokeDisabled: 'rgba(0,0,0,0.35)',
//   colorControlBackgroundListItemSelectedFillRest: 'rgba(114,117,192,0.12)',
//   colorControlBackgroundListItemSelectedFillHover: 'rgba(114,117,192,0.22)',
//   colorControlBackgroundListItemSelectedFillPressed: 'rgba(114,117,192,0.08)',
//   colorControlBackgroundListItemSelectedFillDisabled: 'rgba(114,117,192,0.0)',
//   colorControlBackgroundListItemSelectedIndicatorFillRest: '#6C70BA',
//   colorControlBackgroundListItemSelectedIndicatorFillHover: '#6166AF',
//   colorControlBackgroundListItemSelectedIndicatorFillPressed: '#7275C0',
//   colorControlBackgroundListItemSelectedIndicatorFillDisabled: 'rgba(114,117,192,0.35)',
//   colorControlBackgroundAccentShapeSafeFillRest: '#F0494C',
//   colorControlBackgroundAccentShapeSafeFillHover: '#F0494C',
//   colorControlBackgroundAccentShapeSafeFillPressed: 'rgba(240,73,76,0.8)',
//   colorControlBackgroundAccentShapeSafeFillDisabled: 'rgba(240,73,76,0.35)',
//   colorControlBackgroundActiveAccentShapeSafeFillRest: '#7275C0',
//   colorControlBackgroundActiveAccentShapeSafeFillHover: '#6C70BA',
//   colorControlBackgroundActiveAccentShapeSafeFillPressed: '#7275C0',
//   colorControlBackgroundActiveAccentShapeSafeFillDisabled: 'rgba(114,117,192,0.35)',
//   colorControlBackgroundDefaultShapeSafeFillRest: 'rgba(0,0,0,0.45)',
//   colorControlBackgroundDefaultShapeSafeFillHover: 'rgba(0,0,0,0.45)',
//   colorControlBackgroundDefaultShapeSafeFillPressed: 'rgba(0,0,0,0.45)',
//   colorControlBackgroundDefaultShapeSafeFillDisabled: 'rgba(0,0,0,0.35)',
//   colorControlBackgroundDefaultSelectedFillRest: '#7275C0',
//   colorControlBackgroundDefaultSelectedFillHover: '#6266AF',
//   colorControlBackgroundDefaultSelectedFillPressed: 'rgba(114,117,192,0.9)',
//   colorControlBackgroundDefaultSelectedFillDisabled: 'rgba(114,117,192,0.6)',
//   colorControlBackgroundDefaultSelectedStrokeRest: 'rgba(0,0,0,0)',
//   colorControlBackgroundDefaultSelectedStrokeHover: 'rgba(0,0,0,0)',
//   colorControlBackgroundDefaultSelectedStrokePressed: 'rgba(0,0,0,0)',
//   colorControlBackgroundDefaultSelectedStrokeDisabled: 'rgba(0,0,0,0)',
//   colorControlBackgroundDefaultFillRest: 'rgba(114,117,192, 0.12)',
//   colorControlBackgroundDefaultFillHover: 'rgba(114,117,192, 0.22)',
//   colorControlBackgroundDefaultFillPressed: 'rgba(114,117,192, 0.08)',
//   colorControlBackgroundDefaultFillDisabled: 'rgba(114,117,192, 0.04)',
//   colorControlBackgroundDefaultStrokeRest: 'rgba(0,0,0,0)',
//   colorControlBackgroundDefaultStrokeHover: 'rgba(0,0,0,0)',
//   colorControlBackgroundDefaultStrokePressed: 'rgba(0,0,0,0)',
//   colorControlBackgroundDefaultStrokeDisabled: 'rgba(0,0,0,0)',
//   colorControlBackgroundDefaultBottomStrokeRest: 'rgba(0,0,0,0)',
//   colorControlBackgroundDefaultBottomStrokeHover: 'rgba(0,0,0,0)',
//   colorControlBackgroundDefaultBottomStrokePressed: 'rgba(0,0,0,0)',
//   colorControlBackgroundDefaultBottomStrokeDisabled: 'rgba(0,0,0,0)',
//   colorControlBackgroundTextboxFillRest: 'rgba(214,213,255,0)',
//   colorControlBackgroundTextboxFillHover: 'rgba(214,213,255,0)',
//   colorControlBackgroundTextboxFillPressed: 'rgba(214,213,255,0.35)',
//   colorControlBackgroundTextboxFillDisabled: 'rgba(214,213,255,0)',
//   colorControlBackgroundTextboxFillSelected: '#FFFFFF',
//   colorControlBackgroundTextboxStrokeRest: 'rgba(0,0,0,0.45)',
//   colorControlBackgroundTextboxStrokeHover: '#7275C0',
//   colorControlBackgroundTextboxStrokePressed: '#7275C0',
//   colorControlBackgroundTextboxStrokeDisabled: 'rgba(0,0,0,0.35)',
//   colorControlBackgroundTextboxStrokeSelected: '#7275C0',
//   colorControlBackgroundTextboxTextboxUnderlineRest: 'rgba(0,0,0,0)',
//   colorControlBackgroundTextboxTextboxUnderlineHover: 'rgba(0,0,0,0)',
//   colorControlBackgroundTextboxTextboxUnderlinePressed: 'rgba(0,0,0,0)',
//   colorControlBackgroundTextboxTextboxUnderlineDisabled: 'rgba(0,0,0,0)',
//   colorControlBackgroundTextboxTextboxUnderlineSelected: 'rgba(0,0,0,0)',
//   colorControlBackgroundTextboxCursorRest: '#6C70BA',
//   colorControlBackgroundSubtleFillRest: 'rgba(114,117,192,0)',
//   colorControlBackgroundSubtleFillHover: 'rgba114,117,192,0.22)',
//   colorControlBackgroundSubtleFillPressed: 'rgba(114,117,192,0.08)',
//   colorControlBackgroundSubtleFillDisabled: 'rgba(114,117,192,0)',
//   colorControlBackgroundSubtleStrokeRest: 'rgba(0,0,0,0)',
//   colorControlBackgroundSubtleStrokeHover: 'rgba(0,0,0,0)',
//   colorControlBackgroundSubtleStrokePressed: 'rgba(0,0,0,0)',
//   colorControlBackgroundSubtleStrokeDisabled: 'rgba(0,0,0,0)',
//   colorControlBackgroundSubtleSelectedFillRest: 'rgba(114,117,192,0)',
//   colorControlBackgroundSubtleSelectedFillHover: 'rgba114,117,192,0.22)',
//   colorControlBackgroundSubtleSelectedFillPressed: 'rgba(114,117,192,0.08)',
//   colorControlBackgroundSubtleSelectedFillDisabled: 'rgba(114,117,192,0)',
//   colorControlBackgroundAccentFillRest: '#FF5757',
//   colorControlBackgroundAccentFillHover: '#D02835',
//   colorControlBackgroundAccentFillPressed: 'rgba(255,87,87,0.9)',
//   colorControlBackgroundAccentFillDisabled: 'rgba(255,87,87,0.6)',
//   colorControlBackgroundAccentStrokeRest: 'rgba(0,0,0,0)',
//   colorControlBackgroundAccentStrokeHover: 'rgba(0,0,0,0)',
//   colorControlBackgroundAccentStrokePressed: 'rgba(0,0,0,0)',
//   colorControlBackgroundAccentStrokeDisabled: 'rgba(0,0,0,0)',
//   colorControlBackgroundAccentSelectedFillRest: '#7275C0',
//   colorControlBackgroundAccentSelectedFillHover: '#6266AF',
//   colorControlBackgroundAccentSelectedFillPressed: 'rgba(114,117,192,0.9)',
//   colorControlBackgroundAccentSelectedFillDisabled: 'rgba(114,117,192,0.6)',
//   colorControlBackgroundAccentSelectedStrokeRest: 'rgba(255,255,255,0)',
//   colorControlBackgroundAccentSelectedStrokeHover: 'rgba(255,255,255,0)',
//   colorControlBackgroundAccentSelectedStrokePressed: 'rgba(255,255,255,0)',
//   colorControlBackgroundAccentSelectedStrokeDisabled: 'rgba(255,255,255,0)',
//   colorControlBackgroundOutlineSafeFillRest: 'rgba(114,117,192,0)',
//   colorControlBackgroundOutlineSafeFillHover: 'rgba(114,117,192,0)',
//   colorControlBackgroundOutlineSafeFillPressed: 'rgba(114,117,192,0)',
//   colorControlBackgroundOutlineSafeFillDisabled: 'rgba(114,117,192,0)',
//   colorControlBackgroundOutlineSafeStrokeRest: 'rgba(0,0,0,0.45)',
//   colorControlBackgroundOutlineSafeStrokeHover: '#7275C0',
//   colorControlBackgroundOutlineSafeStrokePressed: '#7275C0',
//   colorControlBackgroundOutlineSafeStrokeDisabled: 'rgba(0,0,0,0.35)',
//   colorControlForegroundOnListItemSelectedRest: '#6C70BA',
//   colorControlForegroundOnListItemSelectedHover: '#6166AF',
//   colorControlForegroundOnListItemSelectedPressed: '#7275C0',
//   colorControlForegroundOnListItemSelectedDisabled: 'rgba(114,117,192,0.35)',
//   colorControlForegroundOnListItemSelectedIndicatorRest: '#FFFFFF',
//   colorControlForegroundOnListItemSelectedIndicatorHover: '#FFFFFF',
//   colorControlForegroundOnListItemSelectedIndicatorPressed: '#FFFFFF',
//   colorControlForegroundOnListItemSelectedIndicatorDisabled: '#FFFFFF',
//   colorControlForegroundOnListItemIndicatorHover: 'rgba(97,102,175,0)',
//   colorControlForegroundOnListItemIndicatorPressed: '#7275C0',
//   colorControlForegroundOnSubtleSelectedTextRest: '#6C70BA',
//   colorControlForegroundOnSubtleSelectedTextHover: '#6166AF',
//   colorControlForegroundOnSubtleSelectedTextPressed: '#7275C0',
//   colorControlForegroundOnSubtleSelectedTextDisabled: 'rgba(114,117,192,0.35)',
//   colorControlForegroundOnSubtleSelectedIconRest: '#6C70BA',
//   colorControlForegroundOnSubtleSelectedIconHover: '#6C70BA',
//   colorControlForegroundOnSubtleSelectedIconPressed: '#7275C0',
//   colorControlForegroundOnSubtleSelectedIconDisabled: 'rgba(114,117,192,0.35)',
//   colorControlForegroundOnDefaultSelectedRest: '#FFFFFF',
//   colorControlForegroundOnDefaultSelectedHover: '#FFFFFF',
//   colorControlForegroundOnDefaultSelectedPressed: '#FFFFFF',
//   colorControlForegroundOnDefaultSelectedDisabled: '#FFFFFF',
//   colorControlForegroundPrimaryRest: 'rgba(0,0,0,0.86)',
//   colorControlForegroundPrimaryHover: 'rgba(0,0,0,0.7)',
//   colorControlForegroundPrimaryPressed: 'rgba(0,0,0,0.6)',
//   colorControlForegroundPrimaryDisabled: 'rgba(0,0,0,0.35)',
//   colorControlForegroundSecondaryRest: 'rgba(0,0,0,0.7)',
//   colorControlForegroundSecondaryHover: 'rgba(0,0,0,0.86)',
//   colorControlForegroundSecondaryPressed: 'rgba(0,0,0,0.6)',
//   colorControlForegroundSecondaryDisabled: 'rgba(0,0,0,0.35)',
//   colorControlForegroundTertiaryRest: 'rgba(0,0,0,0.7)',
//   colorControlForegroundTertiaryHover: 'rgba(0,0,0,0.6)',
//   colorControlForegroundTertiaryPressed: 'rgba(0,0,0,0.45)',
//   colorControlForegroundTertiaryDisabled: 'rgba(0,0,0,0.35)',
//   colorControlForegroundPlaceholderRest: 'rgba(0,0,0,0.7)',
//   colorControlForegroundPlaceholderHover: 'rgba(0,0,0,0.86)',
//   colorControlForegroundPlaceholderPressed: 'rgba(0,0,0,0.6)',
//   colorControlForegroundPlaceholderDisabled: 'rgba(0,0,0,0.35)',
//   colorControlForegroundAccentRest: '#DD363E',
//   colorControlForegroundAccentHover: '#D02835',
//   colorControlForegroundAccentHover2: '#A30016',
//   colorControlForegroundAccentPressed: '#F0494C',
//   colorControlForegroundAccentPressed2: '#F0494C',
//   colorControlForegroundAccentDisabled: 'rgba(240,73,76,0.35)',
//   colorControlForegroundActiveAccentRest: '#6C70BA',
//   colorControlForegroundActiveAccentHover: '#6166AF',
//   colorControlForegroundActiveAccentPressed: '#7275C0',
//   colorControlForegroundActiveAccentDisabled: 'rgba(114,117,192,0.35)',
//   colorControlForegroundLightUpRest: 'rgba(0,0,0,0.86)',
//   colorControlForegroundLightUpHover: '#6C70BA',
//   colorControlForegroundLightUpHover2: '#6C70BA',
//   colorControlForegroundLightUpPressed: '#7275C0',
//   colorControlForegroundLightUpPressed2: '#7275C0',
//   colorControlForegroundLightUpDisabled: 'rgba(0,0,0,0.35)',
//   colorControlForegroundOnAccentRest: '#FFFFFF',
//   colorControlForegroundOnAccentHover: '#FFFFFF',
//   colorControlForegroundOnAccentPressed: '#FFFFFF',
//   colorControlForegroundOnAccentDisabled: 'rgba(255,255,255,0.5)',
//   colorControlForegroundOnActiveAccentRest: '#FFFFFF',
//   colorControlForegroundOnActiveAccentHover: '#FFFFFF',
//   colorControlForegroundOnActiveAccentPressed: '#FFFFFF',
//   colorControlForegroundOnActiveAccentDisabled: '#FFFFFF',
//   colorControlPartFocusStrokeInner: '#FFFFFF',
//   colorControlPartFocusStrokeOuter: '#6C70BA',
//   colorControlBackgroundSliderThumbOuterStrokeRest: '#F0494C',
//   colorControlBackgroundSliderThumbOuterStrokeHover: '#F0494C',
//   colorControlBackgroundSliderThumbOuterStrokePressed: 'rgba(240,73,76,0.8)',
//   colorControlBackgroundSliderThumbOuterStrokeDisabled: 'rgba(240,73,76,0.35)',
//   colorControlPartSliderThumbInnerRest: 'rgba(0,0,0,0)',
//   colorControlPartSliderThumbInnerHover: 'rgba(0,0,0,0)',
//   colorControlPartSliderThumbInnerPressed: 'rgba(0,0,0,0)',
//   colorControlPartSliderThumbInnerDisabled: 'rgba(0,0,0,0)',
//   colorControlPartSliderThumbOuterFillRest: 'rgba(0,0,0,0)',
//   colorControlPartSliderThumbOuterFillHover: 'rgba(0,0,0,0)',
//   colorControlPartSliderThumbOuterFillPressed: 'rgba(0,0,0,0)',
//   colorControlPartSliderThumbOuterFillDisabled: 'rgba(0,0,0,0)',
//   colorInfoStatusForegroundOnTaskAccentPrimary: '#FFFFFF',
//   colorInfoStatusBackgroundTaskAccentRest: '#6C70BA',
//   colorPageBackgroundPrimary: '#FFFFFF',
//   colorPageBackgroundSecondary: '#F9F9F9',
//   colorPageBackgroundTertiary: '#F5F5F5',
//   colorPageBackgroundQuarternary: '#F0F0F0',
//   colorPageTextPrimary: 'rgba(0,0,0,0.86)',
//   colorPageTextSecondary: 'rgba(0,0,0,0.7)',
//   colorPageTextDisabled: 'rgba(0,0,0,0.35)',
//   colorPageStrokePrimary: 'rgba(0,0,0,0)',
//   colorPageStrokeFlyout: 'rgba(0,0,0,0)',
//   colorPageDividerDefault: 'rgba(0,0,0,0.1)',
//   colorPageFlyoutBackgroundPrimary: '#FFFFFF',
//   colorPageFlyoutBackgroundSecondary: '#F5F5F5',
//   colorPageLayerDefault: 'rgba(255,255,255,0.5)',
//   colorCardPrimaryFillRest: '#FFFFFF',
//   colorCardPrimaryFillHover: '#FFFFFF',
//   colorCardPrimaryFillPressed: '#FFFFFF',
//   colorCardPrimaryFillDisabled: '#FFFFFF',
//   colorCardPrimaryStrokeRest: 'rgba(0,0,0,0)',
//   colorCardPrimaryStrokeHover: 'rgba(0,0,0,0)',
//   colorCardPrimaryStrokePressed: 'rgba(0,0,0,0)',
//   colorCardPrimaryStrokeDisabled: 'rgba(0,0,0,0)',
//   colorCardSecondaryFillRest: 'rgba(114,117,192,0.1)',
//   colorCardSecondaryFillHover: 'rgba(114,117,192,0.12)',
//   colorCardSecondaryFillPressed: 'rgba(114,117,192,0.08)',
//   colorCardSecondaryFillDisabled: 'rgba(114,117,192,0.04)',
//   colorCardSecondaryStrokeRest: 'rgba(0,0,0,0)',
//   colorCardSecondaryStrokeHover: 'rgba(0,0,0,0)',
//   colorCardSecondaryStrokePressed: 'rgba(0,0,0,0)',
//   colorCardSecondaryStrokeDisabled: 'rgba(0,0,0,0)',
//   colorCardTaskAccentFillRest: 'rgba(114,117,192,0.22)',
//   colorCardTaskAccentFillHover: 'rgba(114,117,192,0.24)',
//   colorCardTaskAccentFillPressed: 'rgba(114,117,192,0.2)',
//   colorCardTaskAccentFillDisabled: 'rgba(114,117,192,0.16)',
//   colorCardTaskAccentStrokeRest: 'rgba(0,0,0,0)',
//   colorCardTaskAccentStrokeHover: 'rgba(0,0,0,0)',
//   colorCardTaskAccentStrokePressed: 'rgba(0,0,0,0)',
//   colorCardTaskAccentStrokeDisabled: 'rgba(0,0,0,0)',
//   colorIllustrationStroke1: 'rgba(255,255,255,0)',
//   colorIllustrationTransparentSurface: '#FFFFFF',
//   colorAcrylicFlyoutDefaultColor: 'rgba(252,252,252,0)',
//   colorAcrylicFlyoutDefaultLuminosity: 'rgba(252,252,252,0.85)',
// });

// export const generateNewCorners = (): NewBorderRadius => ({
//   layoutCornerLayerDefault: "20px",
//   layoutCornerLayerIntersection: "20px",
//   layoutCornerControlDefaultRest: "16px",
//   layoutCornerControlDefaultHover: "18px",
//   layoutCornerControlDefaultPressed: "20px",
//   layoutCornerControlDefaultDisabled: "16px",
//   layoutCornerControRadioHover: "8px",
//   layoutCornerControRadioInnerHover: "6px",
//   layoutCornerControlCheckboxRest: "10px",
//   layoutCornerControlCheckboxHover: "10px",
//   layoutCornerControlCheckboxPressed: "12px",
//   layoutCornerControlCheckboxDisabled: "8px",
//   layoutCornerControlSelectorRest: "999px",
//   layoutCornerCardDefaultRest: "20px",
//   layoutCornerCardDefaultHover: "22px",
//   layoutCornerCardDefaultPressed: "24px",
//   layoutCornerCardDefaultDisabled: "20px",
//   layoutCornerCardLargeRest: "24px",
//   layoutCornerCardLargeHover: "26px",
//   layoutCornerCardLargePressed: "28px",
//   layoutCornerCardLargeDisabled: "24px",
//   layoutCornerToolbarDefault: "20px",
//   layoutCornerTooltipDefault: "24px",
//   layoutCornerFlyoutRest: "24px",
//   layoutCornerFlyoutHover: "28px",
//   layoutCornerFlyoutPressed: "32px",
//   layoutCornerDialog: "24px",
//   layoutCornerOSWindowActive: "20px",
//   layoutCornerOSWindowinactive: "20px",
//   layoutCornerOSShellDefault: "24px",
// })

// export const generateControlLayoutValues = (): NewControlLayout => ({
//   layoutControlButtonDefaultPillHeightRest: '12px',
//   layoutControlButtonDefaultPillHeightHover: '14px',
//   layoutControlButtonDefaultPillHeightPressed: '10px',
//   layoutControlButtonDefaultPillHeightDisabled: '8px',
//   layoutControlButtonDefaultGapIconToText: '0',
//   layoutControlButtonDefaultGapTextToIcon: '0',
//   layoutControlButtonDefaultPaddingPaddingVertical: '10px',
//   layoutControlButtonDefaultPaddingPaddingHorizontal: '10px',
//   layoutControlButtonDefaultPaddingTextWrapperHorizontal: '6px',
//   layoutControlButtonLargePaddingTextWrapperVertical: '2px',
//   layoutControlButtonLargePaddingOuterVertical: '16px',
//   layoutControlButtonLargePaddingOuterHorizontal: '24px',
//   layoutControlButtonLargeGapBetweenIconAndText: '12px',
//   layoutControlButtonStrokeDefaultRest: '1px',
//   layoutControlButtonStrokeOutlineRest: '1px',
//   layoutControlButtonStrokeOutlineHover: '2px',
//   layoutControlButtonStrokeOutlinePressed: '2px',
//   layoutControlButtonStrokeOutlineDisabled: '1px',
//   layoutControlTextboxStrokeOutlineRest: '1px',
//   layoutControlTextboxStrokeOutlineHover: '2px',
//   layoutControlTextboxStrokeOutlinePressed: '2px',
//   layoutControlTextboxStrokeOutlineDisabled: '1px',
//   layoutControlTextboxStrokeOutlineSelected: '1px',
//   layoutControlTextboxStrokeUnderlineRest: '1px',
//   layoutControlTextboxStrokeUnderlineHover: '2px',
//   layoutControlTextboxStrokeUnderlinePressed: '2px',
//   layoutControlTextboxStrokeUnderlineDisabled: '1px',
//   layoutControlTextboxStrokeUnderlineSelected: '2px',
//   layoutControlListItemDefaultPaddingTextWrapperHorizontal: '6px',
//   layoutControlListItemDefaultPaddingOuterHorizontal: '10px',
//   layoutControlListItemDefaultPaddingOutervertical: '10px',
//   layoutControlListItemDefaultGapBetweenSelectors: '8px',
//   layoutControlListItemDefaultGapBetweenIconAndText: '0',
//   layoutControlListItemDefaultFootprintMinWidth: '0',
//   layoutControlSliderThumbFootprintDefault: '24px',
//   layoutControlSliderThumbInnerFootprintRest: '12px',
//   layoutControlSliderThumbInnerFootprintHover: '14px',
//   layoutControlSliderThumbInnerFootprintPressed: '10px',
//   layoutControlSliderThumbInnerFootprintDisabled: '10px',
//   layoutControlSliderThumbOuterFootprintRest: '24px',
//   layoutControlSliderThumbOuterFootprintHover: '24px',
//   layoutControlSliderThumbOuterFootprintPressed: '24px',
//   layoutControlSliderThumbOuterFootprintDisabled: '24px',
//   layoutControlSliderThumbOuterStrokeRest: '1px',
//   layoutControlSliderFootprintHeight: '40px',
//   layoutControlSwitchFootprintDefault: '40px',
//   layoutControlSwitchSizeDefault: '20px',
//   layoutControlSwitchPaddingOuterHorizontal: '4px',
//   layoutControlSwitchGapControlToLabel: '8px',
//   layoutControlSwitchThumbFootprintRest: '12px',
//   layoutControlSwitchThumbFootprintHover: '14px',
//   layoutControlSwitchThumbFootprintPressed: '10px',
//   layoutControlSwitchThumbFootprintDisabled: '12px',
//   layoutControlChatResponseMaxWidth: '800px',
//   layoutControlLinkStrokeDefaultRest: '1px',
//   layoutPageNudgeDefault: '12px',
//   layoutPageGapTextSmall: '4px',
//   layoutPageGapTextMedium: '8px',
//   layoutPageGapItem: '4px',
//   layoutPageGapListItem: '4px',
//   layoutPageGapContainerXS: '8px',
//   layoutPageGapContainerSmall: '16px',
//   layoutPageGapContainerLarge: '40px',
//   layoutPageGapContainerMedium: '28px',
//   layoutPageGapContainerXL: '52px',
//   layoutPageGapNavItem: '4px',
//   layoutPagePaddingToolbarVertical: '4px',
//   layoutPagePaddingToolbarHorizontal: '4px',
//   layoutPagePaddingFlyoutHorizontal: '8px',
//   layoutPagePaddingFlyoutVertical: '8px',
//   layoutPagePaddingPageDefaultHorizontal: '4px',
//   layoutPagePaddingPageDefaultVertical: '16px',
//   layoutPagePaddingPageMediumHorizontal: '16px',
//   layoutPagePaddingPageMediumVertical: '28px',
//   layoutPagePaddingPageLargeHorizontal: '28px',
//   layoutPagePaddingPageLargeVertical: '40px',
//   layoutPagePaddingPageXLHorizontal: '48px',
//   layoutPagePaddingPageXLVertical: '60px',
// })

// export const generateFontSizes = (): FontSizeTokens => ({
//   fontSizeBase100: '10px',
//   fontSizeBase200: '12px',
//   fontSizeBase300: '14px',
//   fontSizeBase400: '16px',
//   fontSizeBase500: '20px',
//   fontSizeBase600: '24px',

//   fontSizeHero700: '28px',
//   fontSizeHero800: '32px',
//   fontSizeHero900: '40px',
//   fontSizeHero1000: '68px',
// });

// export const generateLineHeights = ():  LineHeightTokens => ({
//   lineHeightBase100: '14px',
//   lineHeightBase200: '16px',
//   lineHeightBase300: '20px',
//   lineHeightBase400: '22px',
//   lineHeightBase500: '28px',
//   lineHeightBase600: '32px',

//   lineHeightHero700: '36px',
//   lineHeightHero800: '40px',
//   lineHeightHero900: '52px',
//   lineHeightHero1000: '92px',
// });

// export const generateFontWeights = (): FontWeightTokens => ({
//   fontWeightRegular: 400,
//   fontWeightMedium: 500,
//   fontWeightSemibold: 600,
//   fontWeightBold: 700,
// });

// export const generateFontFamilies = (): FontFamilyTokens => ({
//   fontFamilyBase:
//     // eslint-disable-next-line @fluentui/max-len
//     "'Segoe Sans', 'Segoe UI Web (West European)', -apple-system, BlinkMacSystemFont, Roboto, 'Helvetica Neue', sans-serif",
//   fontFamilyMonospace: "Consolas, 'Courier New', Courier, monospace",
//   fontFamilyNumeric:
//     // eslint-disable-next-line @fluentui/max-len
//     "Bahnschrift, 'Segoe UI', 'Segoe UI Web (West European)', -apple-system, BlinkMacSystemFont, Roboto, 'Helvetica Neue', sans-serif",
// });

// export const generateStrokeWidths = (): StrokeWidthTokens => ({
//   strokeWidthThin: '1px',
//   strokeWidthThick: '2px',
//   strokeWidthThicker: '3px',
//   strokeWidthThickest: '4px',
// });

// export const generateThrowAway = (): ThowAwayForTestingOnly => ({
//   stateBorderSize: '2px',
//   sliderMask: `#FFFFFF`,
//   textInputFocusBottomBorder: "1px",
//   controlHeight: "40px",
//   layoutControlSliderThumbStrokeRest: '6px',
//   layoutControlSliderThumbStrokeHover: '5px',
//   layoutControlSliderThumbStrokePressed: '7px',
//   layoutControlSliderThumbStrokeDisabled: '6px',
// })
